// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/encoder.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEncoder is a mock of Encoder interface.
type MockEncoder struct {
	ctrl     *gomock.Controller
	recorder *MockEncoderMockRecorder
}

// MockEncoderMockRecorder is the mock recorder for MockEncoder.
type MockEncoderMockRecorder struct {
	mock *MockEncoder
}

// NewMockEncoder creates a new mock instance.
func NewMockEncoder(ctrl *gomock.Controller) *MockEncoder {
	mock := &MockEncoder{ctrl: ctrl}
	mock.recorder = &MockEncoderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncoder) EXPECT() *MockEncoderMockRecorder {
	return m.recorder
}

// EncodeToString mocks base method.
func (m *MockEncoder) EncodeToString(src []byte) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncodeToString", src)
	ret0, _ := ret[0].(string)
	return ret0
}

// EncodeToString indicates an expected call of EncodeToString.
func (mr *MockEncoderMockRecorder) EncodeToString(src interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncodeToString", reflect.TypeOf((*MockEncoder)(nil).EncodeToString), src)
}
